Feat: Automplete search Patients
Navi02643/emociones-BE pull request #21
Opened 2022-12-21 00:14 UTC by MiguelAngelSF

2022-12-21 00:20 UTC, FraGa96 requested changes
Endpoint added: Missing swagger documentation

2022-12-21 00:20 UTC, FraGa96 commented on server/routes/users.js
> +    const data = await userService.nameAutoComplete(req.body);
did you mean req.query?
Remember the standar for simple GET verb is usually querystring
api/autocomplete?name=blahblah

2022-12-21 00:27 UTC, MiguelAngelSF commented on server/routes/users.js
> +    const data = await userService.nameAutoComplete(req.body);
Ok I understand, I'll make the change in a moment

2022-12-27 18:49 UTC, FraGa96 approved these changes

2022-12-27 21:52 UTC, Navi02643 approved these changes

2022-12-28 22:44 UTC, FraGa96 approved these changes

2022-12-28 22:47 UTC, FraGa96 requested changes

2022-12-28 22:47 UTC, FraGa96 commented on server/database/users.js
> +  const searchPatient = await UserModel.find({ name: { $regex: `${name}` }, range: 1 });
use constants "Enums" instead of a direct number on range
for example, considering:
```
const RANGE = {
  patient: 1,
  therapist: 2,
  admin: 3,
}
```

use range: RANGE.patient

2022-12-28 22:47 UTC, FraGa96 commented on server/services/appointments.js
> +  if (range === 1) {
Use enums instead of direct numbers as range (check the other comment)

2022-12-29 21:00 UTC, FraGa96 requested changes

2022-12-29 21:00 UTC, FraGa96 commented on server/services/appointments.js
> +const ranges = require("../utils/range.constans");
uppercase please

2022-12-30 17:35 UTC, ErickIsra01 approved these changes

2022-12-30 20:13 UTC, FraGa96 approved these changes

2023-01-03 15:59 UTC, merged