Em 19
Navi02643/emociones-BE pull request #25
Opened 2022-12-28 01:19 UTC by MiguelAngelSF

2022-12-28 02:10 UTC, gfranco-arkus approved these changes

2022-12-28 02:35 UTC, Navi02643 approved these changes

2022-12-28 18:41 UTC, ErickIsra01 commented on server/services/appointments.js
> +  if (range === 1) {
I think this nested if could be changed into an if with two conditions

2022-12-28 22:49 UTC, FraGa96 requested changes

2022-12-28 22:49 UTC, FraGa96 commented on server/database/users.js
> +  const searchPatient = await UserModel.find({ name: { $regex: `${name}` }, range: 1 });
use constants/enums instead of the plain number in range (check comments on PR #21 )

2022-12-29 20:15 UTC, FraGa96 requested changes

2022-12-29 20:15 UTC, FraGa96 commented on server/services/appointments.js
> +const RANGE = {
move this to a different file where you can have all constants, I'm pretty sure you're going to require this constant in other files

2022-12-29 20:43 UTC, FraGa96 requested changes

2022-12-29 20:43 UTC, FraGa96 commented on server/services/appointments.js
> +const ranges = require("../utils/range.constans");
UPPER_CASE please

2022-12-29 20:53 UTC, FraGa96 approved these changes

2022-12-29 20:58 UTC, merged