Feat: Function to create added notes
Navi02643/emociones-BE pull request #45
Opened 2023-01-12 17:50 UTC by Navi02643

2023-01-19 17:23 UTC, FraGa96 requested changes

2023-01-19 17:23 UTC, FraGa96 commented on server/services/models/followDTO.js
> +  const months = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];
if this arrays is used commonly (as I have seen it, I highly recomment to move to the constants file

2023-01-30 15:54 UTC, MiguelAngelSF approved these changes

2023-01-30 16:00 UTC, MiguelAngelSF approved these changes

2023-01-30 16:30 UTC, ErickIsra01 approved these changes

2023-01-30 17:09 UTC, ErickIsra01 approved these changes

2023-01-30 19:29 UTC, FraGa96 approved these changes

2023-01-30 19:29 UTC, FraGa96 commented on server/services/follow.js
> +  if (searchFollow) return { isValid: false, message: 'You cant create a note, edit the previously created note this day.', data: searchFollow._id };
should not this message be in spanish? (genuine question jeje)

2023-01-31 15:56 UTC, ErickIsra01 approved these changes

2023-01-31 15:56 UTC, merged