Em 90 be records service get record
Navi02643/emociones-BE pull request #74
Opened 2023-02-03 15:39 UTC by Navi02643

2023-02-03 16:37 UTC, FraGa96 requested changes

2023-02-03 16:37 UTC, FraGa96 commented on server/services/models/appointmentsDTO.js
> +const FILTERDATE = require('../../utils/getDate.constants');
If you only use filterDate function from this module, you can import it like
```suggestion
const { filterDate } = require('../../utils/getDate.constants');
```

2023-02-03 16:37 UTC, FraGa96 commented on server/services/models/recordsDTO.js
> +const FILTERDATE = require('../../utils/getDate.constants');
same
```suggestion
const { filterDate }= require('../../utils/getDate.constants');
```

2023-02-03 16:37 UTC, FraGa96 commented on server/services/models/recordsDTO.js
> +  return filter;
What if record is empty? 

also in order to reduce all "record[0]" 
you can do:
`const [firstRecord] = record`

this is desctructuring an array
if you have any doubts about it: [click here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

2023-02-07 15:47 UTC, MiguelAngelSF approved these changes

2023-02-08 16:09 UTC, MiguelAngelSF approved these changes

2023-02-09 17:14 UTC, FraGa96 approved these changes

2023-02-09 18:23 UTC, merged

2023-02-09 18:23 UTC, ErickIsra01 approved these changes